home:
    path: /
    controller: App\Controller\HomeController
##userRegister##
registration:
    path: /registration
    controller: App\Controller\User\RegistreController

user_activate:
    path: /activate/{token}
    controller: App\Controller\User\ActivateController

user_resen_activate:
    path: /resen_activate/{id}
    controller: App\Controller\User\ResenActivateTokenController

##userProfiler##
account:
    path: /account
    controller: App\Controller\User\AccountController

edit_user:
    path: /account/edit_user
    controller: App\Controller\User\EditUserController

renew_password:
    path: /user/account/renew_password
    controller: App\Controller\User\Password\RenewPasswordController

forgot_password:
    path: /forgot_password
    controller: App\Controller\User\Password\PasswordController

reset_password:
    path: /reset_password
    controller: App\Controller\User\Password\ResetPasswordController

##userIdentification##
login:
    path: /login
    controller: App\Controller\User\Security\SecurityController

logout:
    path: /logout
    controller: App\Controller\User\Security\SecurityController

##admin##
admin:
    path: /admin
    controller: App\Controller\Admin\DashboardController::index

##allcategories##
allCategories:
    path: /allcategories
    controller: App\Controller\allCategories\AllCategoriesController

garden:
    path: /garden
    controller: App\Controller\allCategories\GardenController

outside:
    path: /outside
    controller: App\Controller\allCategories\OutsideController

house:
    path: /house
    controller: App\Controller\allCategories\HouseController

animals:
    path: /animals
    controller: App\Controller\allCategories\AnimalsController

commitment:
    path: /commitment
    controller: App\Controller\Services\CommitmentController

delivery-retuns:
    path: /delivery-returns
    controller: App\Controller\Services\DeliveryretunsController

fidelity:
    path: /fidelity
    controller: App\Controller\Services\FidelityController

gift-card:
    path: /gift-card
    controller: App\Controller\Services\GiftcardController

##information##
newsletter:
    path: /newsletter
    controller: App\Controller\contact\NewsletterController

contact:
    path: /contact
    controller: App\Controller\contact\ContactController

